// Code generated by internal/gen/memarggen. DO NOT EDIT.
//
// Authority:  third_party/spec/interpreter/text/lexer.mll
//             at bdd7164bfe18cf0bd5c3d90ef8cc3b8919fb9c0a — the core spec at bdd7164: every clause of the MVP and of the nine shipped proposals
//             45 rows (LOAD 19, STORE 4, VEC_LOAD 13, VEC_LOAD_LANE 4, VEC_STORE 1, VEC_STORE_LANE 4)
// Authority:  third_party/spec-threads/interpreter/text/lexer.mll
//             at cc535ada1aa21cfaa3cabf3ac73b89acef78a0a0 — the threads proposal at cc535ad, and *only* its threads clauses — its baseline predates GC and memory64, so a wholesale read of any of its files deletes both: 102 of lexer.mll's keywords are core-only, against the 70 it adds
//             66 rows (ATOMIC_LOAD 2, ATOMIC_RMW 42, ATOMIC_RMW_CMPXCHG 7, ATOMIC_STORE 12, MEMORY_ATOMIC_NOTIFY 1, MEMORY_ATOMIC_WAIT 2)
// Extractor:  memarggen v2
// Rows:       111
//
// The natural alignment each memory-accessing mnemonic defaults to when the text omits
// `align=`. Machine-derived per decision 0007's argument: the default is not in the text, so
// a wrong one produces an image that **decodes clean** and differs from the source only in a
// flags byte no assert_malformed inspects — invisible on the board by construction
// (contract §9 G-3).
//
// The values are log2 exponents, which is the form both authorities use: parser.mly:532's
// `align` production log2s the byte count the text writes, and encode.ml:221's `memop`
// writes the exponent straight into the flags field. So the number here is the number the
// flags byte holds.
//
// **More than one authority, because the grammar is the union of the tracked set** (§9 G-2), and
// the composition is base-wins for keywordgen's measured reason: the pins do not share a
// baseline, so a wholesale read of a proposal pin deletes core rows rather than adding its own.
// Each row's citation therefore names its *file* and not just a line — two pins put two files
// named lexer.mll in the tree, and a bare "lexer.mll:266" resolves against whichever one the
// reader opens (grave #529). For the atomic rows the default is also the only *legal* alignment,
// every atomic access being naturally aligned by the proposal's own validation rule, so a wrong
// row there is a rejected module rather than a slow one.
//
// Regenerate with 'make memarg'; 'make memarg-drift' asserts this file still agrees with every
// pinned reference above.

package text

// naturalAlign is the log2 alignment a memory-accessing mnemonic defaults to.
//
// A mnemonic **absent** from this map takes no memarg. That is load-bearing rather than
// incidental: `immediates`'s memarg arm looks the mnemonic up and a miss is a refusal, so a
// mnemonic dropped from this table becomes an unencodable instruction rather than one encoded
// with a zero alignment.
var naturalAlign = map[string]uint32{
	"f32.load":                   2, // LOAD                 spec/lexer.mll:247
	"f32.store":                  2, // STORE                spec/lexer.mll:251
	"f64.load":                   3, // LOAD                 spec/lexer.mll:248
	"f64.store":                  3, // STORE                spec/lexer.mll:252
	"i32.atomic.load":            2, // ATOMIC_LOAD          spec-threads/lexer.mll:267
	"i32.atomic.load16_u":        1, // ATOMIC_STORE         spec-threads/lexer.mll:282
	"i32.atomic.load8_u":         0, // ATOMIC_STORE         spec-threads/lexer.mll:279
	"i32.atomic.rmw.add":         2, // ATOMIC_RMW           spec-threads/lexer.mll:309
	"i32.atomic.rmw.and":         2, // ATOMIC_RMW           spec-threads/lexer.mll:315
	"i32.atomic.rmw.cmpxchg":     2, // ATOMIC_RMW_CMPXCHG   spec-threads/lexer.mll:435
	"i32.atomic.rmw.or":          2, // ATOMIC_RMW           spec-threads/lexer.mll:318
	"i32.atomic.rmw.sub":         2, // ATOMIC_RMW           spec-threads/lexer.mll:312
	"i32.atomic.rmw.xchg":        2, // ATOMIC_RMW           spec-threads/lexer.mll:324
	"i32.atomic.rmw.xor":         2, // ATOMIC_RMW           spec-threads/lexer.mll:321
	"i32.atomic.rmw16.add_u":     1, // ATOMIC_RMW           spec-threads/lexer.mll:381
	"i32.atomic.rmw16.and_u":     1, // ATOMIC_RMW           spec-threads/lexer.mll:387
	"i32.atomic.rmw16.cmpxchg_u": 1, // ATOMIC_RMW_CMPXCHG   spec-threads/lexer.mll:447
	"i32.atomic.rmw16.or_u":      1, // ATOMIC_RMW           spec-threads/lexer.mll:390
	"i32.atomic.rmw16.sub_u":     1, // ATOMIC_RMW           spec-threads/lexer.mll:384
	"i32.atomic.rmw16.xchg_u":    1, // ATOMIC_RMW           spec-threads/lexer.mll:396
	"i32.atomic.rmw16.xor_u":     1, // ATOMIC_RMW           spec-threads/lexer.mll:393
	"i32.atomic.rmw8.add_u":      0, // ATOMIC_RMW           spec-threads/lexer.mll:345
	"i32.atomic.rmw8.and_u":      0, // ATOMIC_RMW           spec-threads/lexer.mll:351
	"i32.atomic.rmw8.cmpxchg_u":  0, // ATOMIC_RMW_CMPXCHG   spec-threads/lexer.mll:441
	"i32.atomic.rmw8.or_u":       0, // ATOMIC_RMW           spec-threads/lexer.mll:354
	"i32.atomic.rmw8.sub_u":      0, // ATOMIC_RMW           spec-threads/lexer.mll:348
	"i32.atomic.rmw8.xchg_u":     0, // ATOMIC_RMW           spec-threads/lexer.mll:360
	"i32.atomic.rmw8.xor_u":      0, // ATOMIC_RMW           spec-threads/lexer.mll:357
	"i32.atomic.store":           2, // ATOMIC_STORE         spec-threads/lexer.mll:273
	"i32.atomic.store16":         1, // ATOMIC_STORE         spec-threads/lexer.mll:297
	"i32.atomic.store8":          0, // ATOMIC_STORE         spec-threads/lexer.mll:294
	"i32.load":                   2, // LOAD                 spec/lexer.mll:245
	"i32.load16_s":               1, // LOAD                 spec/lexer.mll:257
	"i32.load16_u":               1, // LOAD                 spec/lexer.mll:256
	"i32.load8_s":                0, // LOAD                 spec/lexer.mll:255
	"i32.load8_u":                0, // LOAD                 spec/lexer.mll:254
	"i32.store":                  2, // STORE                spec/lexer.mll:249
	"i32.store16":                1, // LOAD                 spec/lexer.mll:266
	"i32.store8":                 0, // LOAD                 spec/lexer.mll:265
	"i64.atomic.load":            3, // ATOMIC_LOAD          spec-threads/lexer.mll:270
	"i64.atomic.load16_u":        1, // ATOMIC_STORE         spec-threads/lexer.mll:288
	"i64.atomic.load32_u":        2, // ATOMIC_STORE         spec-threads/lexer.mll:291
	"i64.atomic.load8_u":         0, // ATOMIC_STORE         spec-threads/lexer.mll:285
	"i64.atomic.rmw.add":         3, // ATOMIC_RMW           spec-threads/lexer.mll:327
	"i64.atomic.rmw.and":         3, // ATOMIC_RMW           spec-threads/lexer.mll:333
	"i64.atomic.rmw.cmpxchg":     3, // ATOMIC_RMW_CMPXCHG   spec-threads/lexer.mll:438
	"i64.atomic.rmw.or":          3, // ATOMIC_RMW           spec-threads/lexer.mll:336
	"i64.atomic.rmw.sub":         3, // ATOMIC_RMW           spec-threads/lexer.mll:330
	"i64.atomic.rmw.xchg":        3, // ATOMIC_RMW           spec-threads/lexer.mll:342
	"i64.atomic.rmw.xor":         3, // ATOMIC_RMW           spec-threads/lexer.mll:339
	"i64.atomic.rmw16.add_u":     1, // ATOMIC_RMW           spec-threads/lexer.mll:399
	"i64.atomic.rmw16.and_u":     1, // ATOMIC_RMW           spec-threads/lexer.mll:405
	"i64.atomic.rmw16.cmpxchg_u": 1, // ATOMIC_RMW_CMPXCHG   spec-threads/lexer.mll:450
	"i64.atomic.rmw16.or_u":      1, // ATOMIC_RMW           spec-threads/lexer.mll:408
	"i64.atomic.rmw16.sub_u":     1, // ATOMIC_RMW           spec-threads/lexer.mll:402
	"i64.atomic.rmw16.xchg_u":    1, // ATOMIC_RMW           spec-threads/lexer.mll:414
	"i64.atomic.rmw16.xor_u":     1, // ATOMIC_RMW           spec-threads/lexer.mll:411
	"i64.atomic.rmw32.add_u":     2, // ATOMIC_RMW           spec-threads/lexer.mll:417
	"i64.atomic.rmw32.and_u":     2, // ATOMIC_RMW           spec-threads/lexer.mll:423
	"i64.atomic.rmw32.cmpxchg_u": 2, // ATOMIC_RMW_CMPXCHG   spec-threads/lexer.mll:453
	"i64.atomic.rmw32.or_u":      2, // ATOMIC_RMW           spec-threads/lexer.mll:426
	"i64.atomic.rmw32.sub_u":     2, // ATOMIC_RMW           spec-threads/lexer.mll:420
	"i64.atomic.rmw32.xchg_u":    2, // ATOMIC_RMW           spec-threads/lexer.mll:432
	"i64.atomic.rmw32.xor_u":     2, // ATOMIC_RMW           spec-threads/lexer.mll:429
	"i64.atomic.rmw8.add_u":      0, // ATOMIC_RMW           spec-threads/lexer.mll:363
	"i64.atomic.rmw8.and_u":      0, // ATOMIC_RMW           spec-threads/lexer.mll:369
	"i64.atomic.rmw8.cmpxchg_u":  0, // ATOMIC_RMW_CMPXCHG   spec-threads/lexer.mll:444
	"i64.atomic.rmw8.or_u":       0, // ATOMIC_RMW           spec-threads/lexer.mll:372
	"i64.atomic.rmw8.sub_u":      0, // ATOMIC_RMW           spec-threads/lexer.mll:366
	"i64.atomic.rmw8.xchg_u":     0, // ATOMIC_RMW           spec-threads/lexer.mll:378
	"i64.atomic.rmw8.xor_u":      0, // ATOMIC_RMW           spec-threads/lexer.mll:375
	"i64.atomic.store":           3, // ATOMIC_STORE         spec-threads/lexer.mll:276
	"i64.atomic.store16":         1, // ATOMIC_STORE         spec-threads/lexer.mll:303
	"i64.atomic.store32":         2, // ATOMIC_STORE         spec-threads/lexer.mll:306
	"i64.atomic.store8":          0, // ATOMIC_STORE         spec-threads/lexer.mll:300
	"i64.load":                   3, // LOAD                 spec/lexer.mll:246
	"i64.load16_s":               1, // LOAD                 spec/lexer.mll:261
	"i64.load16_u":               1, // LOAD                 spec/lexer.mll:260
	"i64.load32_s":               2, // LOAD                 spec/lexer.mll:263
	"i64.load32_u":               2, // LOAD                 spec/lexer.mll:262
	"i64.load8_s":                0, // LOAD                 spec/lexer.mll:259
	"i64.load8_u":                0, // LOAD                 spec/lexer.mll:258
	"i64.store":                  3, // STORE                spec/lexer.mll:250
	"i64.store16":                1, // LOAD                 spec/lexer.mll:268
	"i64.store32":                2, // LOAD                 spec/lexer.mll:269
	"i64.store8":                 0, // LOAD                 spec/lexer.mll:267
	"memory.atomic.notify":       2, // MEMORY_ATOMIC_NOTIFY spec-threads/lexer.mll:258
	"memory.atomic.wait32":       2, // MEMORY_ATOMIC_WAIT   spec-threads/lexer.mll:260
	"memory.atomic.wait64":       3, // MEMORY_ATOMIC_WAIT   spec-threads/lexer.mll:263
	"v128.load":                  4, // VEC_LOAD             spec/lexer.mll:271
	"v128.load16_lane":           1, // VEC_LOAD_LANE        spec/lexer.mll:293
	"v128.load16_splat":          1, // VEC_LOAD             spec/lexer.mll:281
	"v128.load16x4_s":            3, // VEC_LOAD             spec/lexer.mll:276
	"v128.load16x4_u":            3, // VEC_LOAD             spec/lexer.mll:275
	"v128.load32_lane":           2, // VEC_LOAD_LANE        spec/lexer.mll:295
	"v128.load32_splat":          2, // VEC_LOAD             spec/lexer.mll:283
	"v128.load32_zero":           2, // VEC_LOAD             spec/lexer.mll:287
	"v128.load32x2_s":            3, // VEC_LOAD             spec/lexer.mll:278
	"v128.load32x2_u":            3, // VEC_LOAD             spec/lexer.mll:277
	"v128.load64_lane":           3, // VEC_LOAD_LANE        spec/lexer.mll:297
	"v128.load64_splat":          3, // VEC_LOAD             spec/lexer.mll:285
	"v128.load64_zero":           3, // VEC_LOAD             spec/lexer.mll:289
	"v128.load8_lane":            0, // VEC_LOAD_LANE        spec/lexer.mll:291
	"v128.load8_splat":           0, // VEC_LOAD             spec/lexer.mll:279
	"v128.load8x8_s":             3, // VEC_LOAD             spec/lexer.mll:274
	"v128.load8x8_u":             3, // VEC_LOAD             spec/lexer.mll:273
	"v128.store":                 4, // VEC_STORE            spec/lexer.mll:272
	"v128.store16_lane":          1, // VEC_STORE_LANE       spec/lexer.mll:301
	"v128.store32_lane":          2, // VEC_STORE_LANE       spec/lexer.mll:303
	"v128.store64_lane":          3, // VEC_STORE_LANE       spec/lexer.mll:305
	"v128.store8_lane":           0, // VEC_STORE_LANE       spec/lexer.mll:299
}
