// Code generated by internal/gen/memarggen. DO NOT EDIT.
//
// Authority:  WebAssembly/spec interpreter/text/lexer.mll
// Revision:   bdd7164bfe18cf0bd5c3d90ef8cc3b8919fb9c0a
// Extractor:  memarggen v1
// Rows:       45
//
// The natural alignment each memory-accessing mnemonic defaults to when the text omits
// `align=`. Machine-derived per decision 0007's argument: the default is not in the text, so
// a wrong one produces an image that **decodes clean** and differs from the source only in a
// flags byte no assert_malformed inspects — invisible on the board by construction
// (contract §9 G-3).
//
// The values are log2 exponents, which is the form both authorities use: parser.mly:532's
// `align` production log2s the byte count the text writes, and encode.ml:221's `memop`
// writes the exponent straight into the flags field. So the number here is the number the
// flags byte holds.
//
// Regenerate with 'make memarg'; 'make memarg-drift' asserts this file still agrees with the
// pinned reference.

package text

// naturalAlign is the log2 alignment a memory-accessing mnemonic defaults to.
//
// A mnemonic **absent** from this map takes no memarg. That is load-bearing rather than
// incidental: `immediates`'s memarg arm looks the mnemonic up and a miss is a refusal, so a
// mnemonic dropped from this table becomes an unencodable instruction rather than one encoded
// with a zero alignment.
var naturalAlign = map[string]uint32{
	"f32.load":          2, // LOAD           lexer.mll:247
	"f32.store":         2, // STORE          lexer.mll:251
	"f64.load":          3, // LOAD           lexer.mll:248
	"f64.store":         3, // STORE          lexer.mll:252
	"i32.load":          2, // LOAD           lexer.mll:245
	"i32.load16_s":      1, // LOAD           lexer.mll:257
	"i32.load16_u":      1, // LOAD           lexer.mll:256
	"i32.load8_s":       0, // LOAD           lexer.mll:255
	"i32.load8_u":       0, // LOAD           lexer.mll:254
	"i32.store":         2, // STORE          lexer.mll:249
	"i32.store16":       1, // LOAD           lexer.mll:266
	"i32.store8":        0, // LOAD           lexer.mll:265
	"i64.load":          3, // LOAD           lexer.mll:246
	"i64.load16_s":      1, // LOAD           lexer.mll:261
	"i64.load16_u":      1, // LOAD           lexer.mll:260
	"i64.load32_s":      2, // LOAD           lexer.mll:263
	"i64.load32_u":      2, // LOAD           lexer.mll:262
	"i64.load8_s":       0, // LOAD           lexer.mll:259
	"i64.load8_u":       0, // LOAD           lexer.mll:258
	"i64.store":         3, // STORE          lexer.mll:250
	"i64.store16":       1, // LOAD           lexer.mll:268
	"i64.store32":       2, // LOAD           lexer.mll:269
	"i64.store8":        0, // LOAD           lexer.mll:267
	"v128.load":         4, // VEC_LOAD       lexer.mll:271
	"v128.load16_lane":  1, // VEC_LOAD_LANE  lexer.mll:293
	"v128.load16_splat": 1, // VEC_LOAD       lexer.mll:281
	"v128.load16x4_s":   3, // VEC_LOAD       lexer.mll:276
	"v128.load16x4_u":   3, // VEC_LOAD       lexer.mll:275
	"v128.load32_lane":  2, // VEC_LOAD_LANE  lexer.mll:295
	"v128.load32_splat": 2, // VEC_LOAD       lexer.mll:283
	"v128.load32_zero":  2, // VEC_LOAD       lexer.mll:287
	"v128.load32x2_s":   3, // VEC_LOAD       lexer.mll:278
	"v128.load32x2_u":   3, // VEC_LOAD       lexer.mll:277
	"v128.load64_lane":  3, // VEC_LOAD_LANE  lexer.mll:297
	"v128.load64_splat": 3, // VEC_LOAD       lexer.mll:285
	"v128.load64_zero":  3, // VEC_LOAD       lexer.mll:289
	"v128.load8_lane":   0, // VEC_LOAD_LANE  lexer.mll:291
	"v128.load8_splat":  0, // VEC_LOAD       lexer.mll:279
	"v128.load8x8_s":    3, // VEC_LOAD       lexer.mll:274
	"v128.load8x8_u":    3, // VEC_LOAD       lexer.mll:273
	"v128.store":        4, // VEC_STORE      lexer.mll:272
	"v128.store16_lane": 1, // VEC_STORE_LANE lexer.mll:301
	"v128.store32_lane": 2, // VEC_STORE_LANE lexer.mll:303
	"v128.store64_lane": 3, // VEC_STORE_LANE lexer.mll:305
	"v128.store8_lane":  0, // VEC_STORE_LANE lexer.mll:299
}
