// Copyright 2026 Scott Friedman. SPDX-License-Identifier: Apache-2.0

package validate

// The vector region's constructor families, one row per 0xfd sub-opcode.
//
// **Derived from the reference, and its provenance is a control rather than a note.** Every row was
// read out of `syntax/mnemonics.ml` at the pinned revision by a script at authorship, and
// `TestVecFamiliesMatchTheReference` re-derives the whole table from that file on every CI run and
// compares **in both directions** — a wrong family, a missing row, and a row the reference does not
// have are three separate failures with three separate messages. So this is not a transcription
// anyone is trusted to have got right: it is a cache of a parse, and the parse is the authority.
//
// That is the same posture `optable.go` has toward `decode.ml` (decision 0007's mechanism B) with
// one difference, stated because the asymmetry is deliberate: 0007's tables are emitted by a
// committed generator with its own `make` target, and this one is a committed map whose generator
// was a one-off. The reason is where the check lives. `internal/validate` already reads `valid.ml`
// under `testenv.RequireSpecRef` for its own authority controls, and CI sets
// `BURROUGHS_NO_SKIP=1` workflow-wide with the reference vendored — so an in-package bidirectional
// test is binding on every run without a fourth generator, a fourth `make` target and a fourth CI
// step. A generator would buy the ability to regenerate on a pin bump; the test already *fails* on
// a pin bump that moves a row, which is the property that matters. If the region ever needs
// regenerating in anger, that is the moment to promote this to `internal/gen`, and the failing test
// is what will say so.
//
// Why the whole region and not the 236 rows this slice types: the relaxed-SIMD rows are inside
// SIMD's opcode range, so a table scoped to what `vecSignature` currently handles would have a
// domain that moves when a gate flips — *scope controls to the space*. The space is the region.

// vecFamilyRow is one mnemonic's classification in the reference's own vocabulary.
//
// `family` is the `valid.ml` arm that types it, `shape` the lane shape the constructor carries (or
// the empty shape for the whole-register families), and `op` the operator constructor inside it.
// `op` is read by exactly one rule — `check_vec_binop`'s shuffle bound — and is carried for every
// row anyway, because a field populated only where it is consumed is a domain that shrinks
// silently the next time something needs it.
type vecFamilyRow struct {
	family string
	shape  vecShape
	op     string
}

// vecFamily maps a 0xfd mnemonic to its row. Keyed by mnemonic rather than by sub-opcode, which is
// the join key the reference itself uses: `decode.ml` says which byte produces which mnemonic and
// `mnemonics.ml` says which family that mnemonic is, so keying by name keeps the two hops visible
// and puts no third opcode declaration in the tree (0014's argument for `mnemonicOpcodes`).
var vecFamily = map[string]vecFamilyRow{
	"v128_load":                           {family: "VecLoad", shape: "", op: ""},
	"v128_load8x8_s":                      {family: "VecLoad", shape: "", op: ""},
	"v128_load8x8_u":                      {family: "VecLoad", shape: "", op: ""},
	"v128_load16x4_s":                     {family: "VecLoad", shape: "", op: ""},
	"v128_load16x4_u":                     {family: "VecLoad", shape: "", op: ""},
	"v128_load32x2_s":                     {family: "VecLoad", shape: "", op: ""},
	"v128_load32x2_u":                     {family: "VecLoad", shape: "", op: ""},
	"v128_load8_splat":                    {family: "VecLoad", shape: "", op: ""},
	"v128_load16_splat":                   {family: "VecLoad", shape: "", op: ""},
	"v128_load32_splat":                   {family: "VecLoad", shape: "", op: ""},
	"v128_load64_splat":                   {family: "VecLoad", shape: "", op: ""},
	"v128_store":                          {family: "VecStore", shape: "", op: ""},
	"v128_const":                          {family: "VecConst", shape: "", op: ""},
	"i8x16_shuffle":                       {family: "VecBinary", shape: "I8x16", op: "Shuffle"},
	"i8x16_swizzle":                       {family: "VecBinary", shape: "I8x16", op: "Swizzle"},
	"i8x16_splat":                         {family: "VecSplat", shape: "I8x16", op: "Splat"},
	"i16x8_splat":                         {family: "VecSplat", shape: "I16x8", op: "Splat"},
	"i32x4_splat":                         {family: "VecSplat", shape: "I32x4", op: "Splat"},
	"i64x2_splat":                         {family: "VecSplat", shape: "I64x2", op: "Splat"},
	"f32x4_splat":                         {family: "VecSplat", shape: "F32x4", op: "Splat"},
	"f64x2_splat":                         {family: "VecSplat", shape: "F64x2", op: "Splat"},
	"i8x16_extract_lane_s":                {family: "VecExtract", shape: "I8x16", op: "Extract"},
	"i8x16_extract_lane_u":                {family: "VecExtract", shape: "I8x16", op: "Extract"},
	"i8x16_replace_lane":                  {family: "VecReplace", shape: "I8x16", op: "Replace"},
	"i16x8_extract_lane_s":                {family: "VecExtract", shape: "I16x8", op: "Extract"},
	"i16x8_extract_lane_u":                {family: "VecExtract", shape: "I16x8", op: "Extract"},
	"i16x8_replace_lane":                  {family: "VecReplace", shape: "I16x8", op: "Replace"},
	"i32x4_extract_lane":                  {family: "VecExtract", shape: "I32x4", op: "Extract"},
	"i32x4_replace_lane":                  {family: "VecReplace", shape: "I32x4", op: "Replace"},
	"i64x2_extract_lane":                  {family: "VecExtract", shape: "I64x2", op: "Extract"},
	"i64x2_replace_lane":                  {family: "VecReplace", shape: "I64x2", op: "Replace"},
	"f32x4_extract_lane":                  {family: "VecExtract", shape: "F32x4", op: "Extract"},
	"f32x4_replace_lane":                  {family: "VecReplace", shape: "F32x4", op: "Replace"},
	"f64x2_extract_lane":                  {family: "VecExtract", shape: "F64x2", op: "Extract"},
	"f64x2_replace_lane":                  {family: "VecReplace", shape: "F64x2", op: "Replace"},
	"i8x16_eq":                            {family: "VecCompare", shape: "I8x16", op: "Eq"},
	"i8x16_ne":                            {family: "VecCompare", shape: "I8x16", op: "Ne"},
	"i8x16_lt_s":                          {family: "VecCompare", shape: "I8x16", op: "Lt"},
	"i8x16_lt_u":                          {family: "VecCompare", shape: "I8x16", op: "Lt"},
	"i8x16_gt_s":                          {family: "VecCompare", shape: "I8x16", op: "Gt"},
	"i8x16_gt_u":                          {family: "VecCompare", shape: "I8x16", op: "Gt"},
	"i8x16_le_s":                          {family: "VecCompare", shape: "I8x16", op: "Le"},
	"i8x16_le_u":                          {family: "VecCompare", shape: "I8x16", op: "Le"},
	"i8x16_ge_s":                          {family: "VecCompare", shape: "I8x16", op: "Ge"},
	"i8x16_ge_u":                          {family: "VecCompare", shape: "I8x16", op: "Ge"},
	"i16x8_eq":                            {family: "VecCompare", shape: "I16x8", op: "Eq"},
	"i16x8_ne":                            {family: "VecCompare", shape: "I16x8", op: "Ne"},
	"i16x8_lt_s":                          {family: "VecCompare", shape: "I16x8", op: "Lt"},
	"i16x8_lt_u":                          {family: "VecCompare", shape: "I16x8", op: "Lt"},
	"i16x8_gt_s":                          {family: "VecCompare", shape: "I16x8", op: "Gt"},
	"i16x8_gt_u":                          {family: "VecCompare", shape: "I16x8", op: "Gt"},
	"i16x8_le_s":                          {family: "VecCompare", shape: "I16x8", op: "Le"},
	"i16x8_le_u":                          {family: "VecCompare", shape: "I16x8", op: "Le"},
	"i16x8_ge_s":                          {family: "VecCompare", shape: "I16x8", op: "Ge"},
	"i16x8_ge_u":                          {family: "VecCompare", shape: "I16x8", op: "Ge"},
	"i32x4_eq":                            {family: "VecCompare", shape: "I32x4", op: "Eq"},
	"i32x4_ne":                            {family: "VecCompare", shape: "I32x4", op: "Ne"},
	"i32x4_lt_s":                          {family: "VecCompare", shape: "I32x4", op: "Lt"},
	"i32x4_lt_u":                          {family: "VecCompare", shape: "I32x4", op: "Lt"},
	"i32x4_gt_s":                          {family: "VecCompare", shape: "I32x4", op: "Gt"},
	"i32x4_gt_u":                          {family: "VecCompare", shape: "I32x4", op: "Gt"},
	"i32x4_le_s":                          {family: "VecCompare", shape: "I32x4", op: "Le"},
	"i32x4_le_u":                          {family: "VecCompare", shape: "I32x4", op: "Le"},
	"i32x4_ge_s":                          {family: "VecCompare", shape: "I32x4", op: "Ge"},
	"i32x4_ge_u":                          {family: "VecCompare", shape: "I32x4", op: "Ge"},
	"f32x4_eq":                            {family: "VecCompare", shape: "F32x4", op: "Eq"},
	"f32x4_ne":                            {family: "VecCompare", shape: "F32x4", op: "Ne"},
	"f32x4_lt":                            {family: "VecCompare", shape: "F32x4", op: "Lt"},
	"f32x4_gt":                            {family: "VecCompare", shape: "F32x4", op: "Gt"},
	"f32x4_le":                            {family: "VecCompare", shape: "F32x4", op: "Le"},
	"f32x4_ge":                            {family: "VecCompare", shape: "F32x4", op: "Ge"},
	"f64x2_eq":                            {family: "VecCompare", shape: "F64x2", op: "Eq"},
	"f64x2_ne":                            {family: "VecCompare", shape: "F64x2", op: "Ne"},
	"f64x2_lt":                            {family: "VecCompare", shape: "F64x2", op: "Lt"},
	"f64x2_gt":                            {family: "VecCompare", shape: "F64x2", op: "Gt"},
	"f64x2_le":                            {family: "VecCompare", shape: "F64x2", op: "Le"},
	"f64x2_ge":                            {family: "VecCompare", shape: "F64x2", op: "Ge"},
	"v128_not":                            {family: "VecUnaryBits", shape: "", op: "Not"},
	"v128_and":                            {family: "VecBinaryBits", shape: "", op: "And"},
	"v128_andnot":                         {family: "VecBinaryBits", shape: "", op: "AndNot"},
	"v128_or":                             {family: "VecBinaryBits", shape: "", op: "Or"},
	"v128_xor":                            {family: "VecBinaryBits", shape: "", op: "Xor"},
	"v128_bitselect":                      {family: "VecTernaryBits", shape: "", op: "Bitselect"},
	"v128_any_true":                       {family: "VecTestBits", shape: "", op: "AnyTrue"},
	"v128_load8_lane":                     {family: "VecLoadLane", shape: "", op: ""},
	"v128_load16_lane":                    {family: "VecLoadLane", shape: "", op: ""},
	"v128_load32_lane":                    {family: "VecLoadLane", shape: "", op: ""},
	"v128_load64_lane":                    {family: "VecLoadLane", shape: "", op: ""},
	"v128_store8_lane":                    {family: "VecStoreLane", shape: "", op: ""},
	"v128_store16_lane":                   {family: "VecStoreLane", shape: "", op: ""},
	"v128_store32_lane":                   {family: "VecStoreLane", shape: "", op: ""},
	"v128_store64_lane":                   {family: "VecStoreLane", shape: "", op: ""},
	"v128_load32_zero":                    {family: "VecLoad", shape: "", op: ""},
	"v128_load64_zero":                    {family: "VecLoad", shape: "", op: ""},
	"f32x4_demote_f64x2_zero":             {family: "VecConvert", shape: "F32x4", op: "DemoteZeroF64x2"},
	"f64x2_promote_low_f32x4":             {family: "VecConvert", shape: "F64x2", op: "PromoteLowF32x4"},
	"i8x16_abs":                           {family: "VecUnary", shape: "I8x16", op: "Abs"},
	"i8x16_neg":                           {family: "VecUnary", shape: "I8x16", op: "Neg"},
	"i8x16_popcnt":                        {family: "VecUnary", shape: "I8x16", op: "Popcnt"},
	"i8x16_all_true":                      {family: "VecTest", shape: "I8x16", op: "AllTrue"},
	"i8x16_bitmask":                       {family: "VecBitmask", shape: "I8x16", op: "Bitmask"},
	"i8x16_narrow_i16x8_s":                {family: "VecBinary", shape: "I8x16", op: "Narrow"},
	"i8x16_narrow_i16x8_u":                {family: "VecBinary", shape: "I8x16", op: "Narrow"},
	"f32x4_ceil":                          {family: "VecUnary", shape: "F32x4", op: "Ceil"},
	"f32x4_floor":                         {family: "VecUnary", shape: "F32x4", op: "Floor"},
	"f32x4_trunc":                         {family: "VecUnary", shape: "F32x4", op: "Trunc"},
	"f32x4_nearest":                       {family: "VecUnary", shape: "F32x4", op: "Nearest"},
	"i8x16_shl":                           {family: "VecShift", shape: "I8x16", op: "Shl"},
	"i8x16_shr_s":                         {family: "VecShift", shape: "I8x16", op: "Shr"},
	"i8x16_shr_u":                         {family: "VecShift", shape: "I8x16", op: "Shr"},
	"i8x16_add":                           {family: "VecBinary", shape: "I8x16", op: "Add"},
	"i8x16_add_sat_s":                     {family: "VecBinary", shape: "I8x16", op: "AddSat"},
	"i8x16_add_sat_u":                     {family: "VecBinary", shape: "I8x16", op: "AddSat"},
	"i8x16_sub":                           {family: "VecBinary", shape: "I8x16", op: "Sub"},
	"i8x16_sub_sat_s":                     {family: "VecBinary", shape: "I8x16", op: "SubSat"},
	"i8x16_sub_sat_u":                     {family: "VecBinary", shape: "I8x16", op: "SubSat"},
	"f64x2_ceil":                          {family: "VecUnary", shape: "F64x2", op: "Ceil"},
	"f64x2_floor":                         {family: "VecUnary", shape: "F64x2", op: "Floor"},
	"i8x16_min_s":                         {family: "VecBinary", shape: "I8x16", op: "Min"},
	"i8x16_min_u":                         {family: "VecBinary", shape: "I8x16", op: "Min"},
	"i8x16_max_s":                         {family: "VecBinary", shape: "I8x16", op: "Max"},
	"i8x16_max_u":                         {family: "VecBinary", shape: "I8x16", op: "Max"},
	"f64x2_trunc":                         {family: "VecUnary", shape: "F64x2", op: "Trunc"},
	"i8x16_avgr_u":                        {family: "VecBinary", shape: "I8x16", op: "AvgrU"},
	"i16x8_extadd_pairwise_i8x16_s":       {family: "VecConvert", shape: "I16x8", op: "ExtAddPairwise"},
	"i16x8_extadd_pairwise_i8x16_u":       {family: "VecConvert", shape: "I16x8", op: "ExtAddPairwise"},
	"i32x4_extadd_pairwise_i16x8_s":       {family: "VecConvert", shape: "I32x4", op: "ExtAddPairwise"},
	"i32x4_extadd_pairwise_i16x8_u":       {family: "VecConvert", shape: "I32x4", op: "ExtAddPairwise"},
	"i16x8_abs":                           {family: "VecUnary", shape: "I16x8", op: "Abs"},
	"i16x8_neg":                           {family: "VecUnary", shape: "I16x8", op: "Neg"},
	"i16x8_q15mulr_sat_s":                 {family: "VecBinary", shape: "I16x8", op: "Q15MulRSatS"},
	"i16x8_all_true":                      {family: "VecTest", shape: "I16x8", op: "AllTrue"},
	"i16x8_bitmask":                       {family: "VecBitmask", shape: "I16x8", op: "Bitmask"},
	"i16x8_narrow_i32x4_s":                {family: "VecBinary", shape: "I16x8", op: "Narrow"},
	"i16x8_narrow_i32x4_u":                {family: "VecBinary", shape: "I16x8", op: "Narrow"},
	"i16x8_extend_low_i8x16_s":            {family: "VecConvert", shape: "I16x8", op: "Extend"},
	"i16x8_extend_high_i8x16_s":           {family: "VecConvert", shape: "I16x8", op: "Extend"},
	"i16x8_extend_low_i8x16_u":            {family: "VecConvert", shape: "I16x8", op: "Extend"},
	"i16x8_extend_high_i8x16_u":           {family: "VecConvert", shape: "I16x8", op: "Extend"},
	"i16x8_shl":                           {family: "VecShift", shape: "I16x8", op: "Shl"},
	"i16x8_shr_s":                         {family: "VecShift", shape: "I16x8", op: "Shr"},
	"i16x8_shr_u":                         {family: "VecShift", shape: "I16x8", op: "Shr"},
	"i16x8_add":                           {family: "VecBinary", shape: "I16x8", op: "Add"},
	"i16x8_add_sat_s":                     {family: "VecBinary", shape: "I16x8", op: "AddSat"},
	"i16x8_add_sat_u":                     {family: "VecBinary", shape: "I16x8", op: "AddSat"},
	"i16x8_sub":                           {family: "VecBinary", shape: "I16x8", op: "Sub"},
	"i16x8_sub_sat_s":                     {family: "VecBinary", shape: "I16x8", op: "SubSat"},
	"i16x8_sub_sat_u":                     {family: "VecBinary", shape: "I16x8", op: "SubSat"},
	"f64x2_nearest":                       {family: "VecUnary", shape: "F64x2", op: "Nearest"},
	"i16x8_mul":                           {family: "VecBinary", shape: "I16x8", op: "Mul"},
	"i16x8_min_s":                         {family: "VecBinary", shape: "I16x8", op: "Min"},
	"i16x8_min_u":                         {family: "VecBinary", shape: "I16x8", op: "Min"},
	"i16x8_max_s":                         {family: "VecBinary", shape: "I16x8", op: "Max"},
	"i16x8_max_u":                         {family: "VecBinary", shape: "I16x8", op: "Max"},
	"i16x8_avgr_u":                        {family: "VecBinary", shape: "I16x8", op: "AvgrU"},
	"i16x8_extmul_low_i8x16_s":            {family: "VecBinary", shape: "I16x8", op: "ExtMul"},
	"i16x8_extmul_high_i8x16_s":           {family: "VecBinary", shape: "I16x8", op: "ExtMul"},
	"i16x8_extmul_low_i8x16_u":            {family: "VecBinary", shape: "I16x8", op: "ExtMul"},
	"i16x8_extmul_high_i8x16_u":           {family: "VecBinary", shape: "I16x8", op: "ExtMul"},
	"i32x4_abs":                           {family: "VecUnary", shape: "I32x4", op: "Abs"},
	"i32x4_neg":                           {family: "VecUnary", shape: "I32x4", op: "Neg"},
	"i32x4_all_true":                      {family: "VecTest", shape: "I32x4", op: "AllTrue"},
	"i32x4_bitmask":                       {family: "VecBitmask", shape: "I32x4", op: "Bitmask"},
	"i32x4_extend_low_i16x8_s":            {family: "VecConvert", shape: "I32x4", op: "Extend"},
	"i32x4_extend_high_i16x8_s":           {family: "VecConvert", shape: "I32x4", op: "Extend"},
	"i32x4_extend_low_i16x8_u":            {family: "VecConvert", shape: "I32x4", op: "Extend"},
	"i32x4_extend_high_i16x8_u":           {family: "VecConvert", shape: "I32x4", op: "Extend"},
	"i32x4_shl":                           {family: "VecShift", shape: "I32x4", op: "Shl"},
	"i32x4_shr_s":                         {family: "VecShift", shape: "I32x4", op: "Shr"},
	"i32x4_shr_u":                         {family: "VecShift", shape: "I32x4", op: "Shr"},
	"i32x4_add":                           {family: "VecBinary", shape: "I32x4", op: "Add"},
	"i32x4_sub":                           {family: "VecBinary", shape: "I32x4", op: "Sub"},
	"i32x4_mul":                           {family: "VecBinary", shape: "I32x4", op: "Mul"},
	"i32x4_min_s":                         {family: "VecBinary", shape: "I32x4", op: "Min"},
	"i32x4_min_u":                         {family: "VecBinary", shape: "I32x4", op: "Min"},
	"i32x4_max_s":                         {family: "VecBinary", shape: "I32x4", op: "Max"},
	"i32x4_max_u":                         {family: "VecBinary", shape: "I32x4", op: "Max"},
	"i32x4_dot_i16x8_s":                   {family: "VecBinary", shape: "I32x4", op: "DotS"},
	"i32x4_extmul_low_i16x8_s":            {family: "VecBinary", shape: "I32x4", op: "ExtMul"},
	"i32x4_extmul_high_i16x8_s":           {family: "VecBinary", shape: "I32x4", op: "ExtMul"},
	"i32x4_extmul_low_i16x8_u":            {family: "VecBinary", shape: "I32x4", op: "ExtMul"},
	"i32x4_extmul_high_i16x8_u":           {family: "VecBinary", shape: "I32x4", op: "ExtMul"},
	"i64x2_abs":                           {family: "VecUnary", shape: "I64x2", op: "Abs"},
	"i64x2_neg":                           {family: "VecUnary", shape: "I64x2", op: "Neg"},
	"i64x2_all_true":                      {family: "VecTest", shape: "I64x2", op: "AllTrue"},
	"i64x2_bitmask":                       {family: "VecBitmask", shape: "I64x2", op: "Bitmask"},
	"i64x2_extend_low_i32x4_s":            {family: "VecConvert", shape: "I64x2", op: "Extend"},
	"i64x2_extend_high_i32x4_s":           {family: "VecConvert", shape: "I64x2", op: "Extend"},
	"i64x2_extend_low_i32x4_u":            {family: "VecConvert", shape: "I64x2", op: "Extend"},
	"i64x2_extend_high_i32x4_u":           {family: "VecConvert", shape: "I64x2", op: "Extend"},
	"i64x2_shl":                           {family: "VecShift", shape: "I64x2", op: "Shl"},
	"i64x2_shr_s":                         {family: "VecShift", shape: "I64x2", op: "Shr"},
	"i64x2_shr_u":                         {family: "VecShift", shape: "I64x2", op: "Shr"},
	"i64x2_add":                           {family: "VecBinary", shape: "I64x2", op: "Add"},
	"i64x2_sub":                           {family: "VecBinary", shape: "I64x2", op: "Sub"},
	"i64x2_mul":                           {family: "VecBinary", shape: "I64x2", op: "Mul"},
	"i64x2_eq":                            {family: "VecCompare", shape: "I64x2", op: "Eq"},
	"i64x2_ne":                            {family: "VecCompare", shape: "I64x2", op: "Ne"},
	"i64x2_lt_s":                          {family: "VecCompare", shape: "I64x2", op: "Lt"},
	"i64x2_gt_s":                          {family: "VecCompare", shape: "I64x2", op: "Gt"},
	"i64x2_le_s":                          {family: "VecCompare", shape: "I64x2", op: "Le"},
	"i64x2_ge_s":                          {family: "VecCompare", shape: "I64x2", op: "Ge"},
	"i64x2_extmul_low_i32x4_s":            {family: "VecBinary", shape: "I64x2", op: "ExtMul"},
	"i64x2_extmul_high_i32x4_s":           {family: "VecBinary", shape: "I64x2", op: "ExtMul"},
	"i64x2_extmul_low_i32x4_u":            {family: "VecBinary", shape: "I64x2", op: "ExtMul"},
	"i64x2_extmul_high_i32x4_u":           {family: "VecBinary", shape: "I64x2", op: "ExtMul"},
	"f32x4_abs":                           {family: "VecUnary", shape: "F32x4", op: "Abs"},
	"f32x4_neg":                           {family: "VecUnary", shape: "F32x4", op: "Neg"},
	"f32x4_sqrt":                          {family: "VecUnary", shape: "F32x4", op: "Sqrt"},
	"f32x4_add":                           {family: "VecBinary", shape: "F32x4", op: "Add"},
	"f32x4_sub":                           {family: "VecBinary", shape: "F32x4", op: "Sub"},
	"f32x4_mul":                           {family: "VecBinary", shape: "F32x4", op: "Mul"},
	"f32x4_div":                           {family: "VecBinary", shape: "F32x4", op: "Div"},
	"f32x4_min":                           {family: "VecBinary", shape: "F32x4", op: "Min"},
	"f32x4_max":                           {family: "VecBinary", shape: "F32x4", op: "Max"},
	"f32x4_pmin":                          {family: "VecBinary", shape: "F32x4", op: "Pmin"},
	"f32x4_pmax":                          {family: "VecBinary", shape: "F32x4", op: "Pmax"},
	"f64x2_abs":                           {family: "VecUnary", shape: "F64x2", op: "Abs"},
	"f64x2_neg":                           {family: "VecUnary", shape: "F64x2", op: "Neg"},
	"f64x2_sqrt":                          {family: "VecUnary", shape: "F64x2", op: "Sqrt"},
	"f64x2_add":                           {family: "VecBinary", shape: "F64x2", op: "Add"},
	"f64x2_sub":                           {family: "VecBinary", shape: "F64x2", op: "Sub"},
	"f64x2_mul":                           {family: "VecBinary", shape: "F64x2", op: "Mul"},
	"f64x2_div":                           {family: "VecBinary", shape: "F64x2", op: "Div"},
	"f64x2_min":                           {family: "VecBinary", shape: "F64x2", op: "Min"},
	"f64x2_max":                           {family: "VecBinary", shape: "F64x2", op: "Max"},
	"f64x2_pmin":                          {family: "VecBinary", shape: "F64x2", op: "Pmin"},
	"f64x2_pmax":                          {family: "VecBinary", shape: "F64x2", op: "Pmax"},
	"i32x4_trunc_sat_f32x4_s":             {family: "VecConvert", shape: "I32x4", op: "TruncSatF32x4"},
	"i32x4_trunc_sat_f32x4_u":             {family: "VecConvert", shape: "I32x4", op: "TruncSatF32x4"},
	"f32x4_convert_i32x4_s":               {family: "VecConvert", shape: "F32x4", op: "ConvertI32x4"},
	"f32x4_convert_i32x4_u":               {family: "VecConvert", shape: "F32x4", op: "ConvertI32x4"},
	"i32x4_trunc_sat_f64x2_s_zero":        {family: "VecConvert", shape: "I32x4", op: "TruncSatZeroF64x2"},
	"i32x4_trunc_sat_f64x2_u_zero":        {family: "VecConvert", shape: "I32x4", op: "TruncSatZeroF64x2"},
	"f64x2_convert_low_i32x4_s":           {family: "VecConvert", shape: "F64x2", op: "ConvertI32x4"},
	"f64x2_convert_low_i32x4_u":           {family: "VecConvert", shape: "F64x2", op: "ConvertI32x4"},
	"i8x16_relaxed_swizzle":               {family: "VecBinary", shape: "I8x16", op: "RelaxedSwizzle"},
	"i32x4_relaxed_trunc_f32x4_s":         {family: "VecConvert", shape: "I32x4", op: "RelaxedTruncF32x4"},
	"i32x4_relaxed_trunc_f32x4_u":         {family: "VecConvert", shape: "I32x4", op: "RelaxedTruncF32x4"},
	"i32x4_relaxed_trunc_f64x2_s_zero":    {family: "VecConvert", shape: "I32x4", op: "RelaxedTruncZeroF64x2"},
	"i32x4_relaxed_trunc_f64x2_u_zero":    {family: "VecConvert", shape: "I32x4", op: "RelaxedTruncZeroF64x2"},
	"f32x4_relaxed_madd":                  {family: "VecTernary", shape: "F32x4", op: "RelaxedMadd"},
	"f32x4_relaxed_nmadd":                 {family: "VecTernary", shape: "F32x4", op: "RelaxedNmadd"},
	"f64x2_relaxed_madd":                  {family: "VecTernary", shape: "F64x2", op: "RelaxedMadd"},
	"f64x2_relaxed_nmadd":                 {family: "VecTernary", shape: "F64x2", op: "RelaxedNmadd"},
	"i8x16_relaxed_laneselect":            {family: "VecTernary", shape: "I8x16", op: "RelaxedLaneselect"},
	"i16x8_relaxed_laneselect":            {family: "VecTernary", shape: "I16x8", op: "RelaxedLaneselect"},
	"i32x4_relaxed_laneselect":            {family: "VecTernary", shape: "I32x4", op: "RelaxedLaneselect"},
	"i64x2_relaxed_laneselect":            {family: "VecTernary", shape: "I64x2", op: "RelaxedLaneselect"},
	"f32x4_relaxed_min":                   {family: "VecBinary", shape: "F32x4", op: "RelaxedMin"},
	"f32x4_relaxed_max":                   {family: "VecBinary", shape: "F32x4", op: "RelaxedMax"},
	"f64x2_relaxed_min":                   {family: "VecBinary", shape: "F64x2", op: "RelaxedMin"},
	"f64x2_relaxed_max":                   {family: "VecBinary", shape: "F64x2", op: "RelaxedMax"},
	"i16x8_relaxed_q15mulr_s":             {family: "VecBinary", shape: "I16x8", op: "RelaxedQ15MulRS"},
	"i16x8_relaxed_dot_i8x16_i7x16_s":     {family: "VecBinary", shape: "I16x8", op: "RelaxedDot"},
	"i32x4_relaxed_dot_i8x16_i7x16_add_s": {family: "VecTernary", shape: "I32x4", op: "RelaxedDotAddS"},
}
